"""
Django settings for TiendaOnlineBack project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(7*ji_&j0j!b2*+n86_@q^96g2^&wfex6psuoz25r6#&%^(p$-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'tiendaonline-backend-yaoo.onrender.com',
    'sage-cannoli-55f8a1.netlify.app',
    'localhost',
    '127.0.0.1',
    "https://res.cloudinary.com",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'TiendaOnline',
    'coreapi',
    'cloudinary',
    'cloudinary_storage',
    

    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TiendaOnlineBack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TiendaOnlineBack.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'uth',
        'USER': 'root',
        'PASSWORD': 'BuFqaxWuhiZAtrWKdDczGmyDeSIQYgaI',
        'HOST': 'interchange.proxy.rlwy.net',
        'PORT': '35864',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# #quien puede acceder a la api
CORS_ALLOWED_ORIGINS = [
    "https://tiendaonline-backend-yaoo.onrender.com",    
    "http://localhost:5173",
    'https://sage-cannoli-55f8a1.netlify.app',
    "https://res.cloudinary.com",
    
]

CORS_ALLOW_ALL_ORIGINS = True

#Metodos permitidos para la api
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'DELETE',    
    'PATCH',
    
]


REST_FRAMEWORK = {

 'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',

}

CSRF_TRUSTED_ORIGINS = [
    'https://tlendsonline-backend-yago.onrender.com',
    'https://sage-cannoli-55f8a1.netlify.app/'  # Reemplaza con tu URL real
]

CSRF_COOKIE_SECURE = True    
SESSION_COOKIE_SECURE = True 

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

#cloudinary 
import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY_STORAGE = {

    'CLOUD_NAME': 'ddf5vvx0b',
    'API_KEY': '652987374643726',
    'API_SECRET': 'Hm8pxE26MFN1uxyEgH2Afjrao2o',
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

