# Generated by Django 5.2 on 2025-05-05 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='El nombre del producto', max_length=255, verbose_name='Nombre del Producto')),
                ('precio', models.DecimalField(decimal_places=2, help_text='El precio del producto', max_digits=10, verbose_name='Precio del Producto')),
                ('cantidad_en_stock', models.IntegerField(help_text='Cantidad disponible en inventario', verbose_name='Cantidad en Stock')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True, verbose_name='Descripción del Producto')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(help_text='El nombre del cliente que realizó el pedido', max_length=255, verbose_name='Nombre del Cliente')),
                ('cantidad', models.IntegerField(help_text='Cantidad de productos en el pedido', verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del pedido', max_digits=10, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total del pedido', max_digits=10, verbose_name='Total')),
                ('direccion', models.CharField(blank=True, help_text='Dirección de entrega', max_length=255, null=True, verbose_name='Dirección')),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico del cliente', max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono del cliente', max_length=20, null=True, verbose_name='Teléfono')),
                ('estado', models.CharField(help_text='Estado actual del pedido', max_length=50, verbose_name='Estado del Pedido')),
                ('descripcion_adicional', models.TextField(blank=True, help_text='Información adicional sobre el pedido', null=True, verbose_name='Descripción Adicional')),
                ('fecha_compra', models.DateField(help_text='Fecha en que se realizó el pedido', verbose_name='Fecha de Compra')),
                ('fecha_entrega', models.DateField(blank=True, help_text='Fecha estimada de entrega', null=True, verbose_name='Fecha de Entrega')),
                ('producto', models.ForeignKey(help_text='El producto asociado al pedido', on_delete=django.db.models.deletion.CASCADE, to='TiendaOnline.producto', verbose_name='Producto')),
            ],
        ),
    ]
