# Generated by Django 5.2 on 2025-05-15 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='El nombre del producto', max_length=255, verbose_name='Nombre del Producto')),
                ('precio', models.DecimalField(decimal_places=2, help_text='El precio del producto', max_digits=10, verbose_name='Precio del Producto')),
                ('cantidad_en_stock', models.IntegerField(help_text='Cantidad disponible en inventario', verbose_name='Cantidad en Stock')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True, verbose_name='Descripción del Producto')),
                ('imagen_base64', models.TextField(blank=True, help_text='Imagen del producto codificada en Base64', null=True, verbose_name='Imagen en Base64')),
                ('categoria', models.CharField(blank=True, choices=[('M', 'Mujeres'), ('H', 'Hombres')], help_text='Tamaño del producto', max_length=3, null=True, verbose_name='Categoria')),
                ('tamaño', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], help_text='Tamaño del producto', max_length=3, null=True, verbose_name='Tamaño')),
                ('colores', models.TextField(default='#FFFFFF', help_text='Color en formato hexadecimal (ej. #FF0000)', verbose_name='Color Hexadecimal')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(help_text='El nombre del cliente que realizó el pedid', max_length=255, verbose_name='Nombre del Cliente')),
                ('apellido_cliente', models.CharField(help_text='El apellido del cliente que realizó el pedido', max_length=255, null=True, verbose_name='Apellido del Cliente')),
                ('cantidad', models.IntegerField(help_text='Cantidad de productos en el pedido', verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del pedido', max_digits=10, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total del pedido', max_digits=10, verbose_name='Total')),
                ('isv', models.DecimalField(decimal_places=2, default=0.15, help_text='Impuesto sobre ventas', max_digits=10, verbose_name='ISV')),
                ('compañia', models.CharField(blank=True, help_text='Compañia a entregar', max_length=255, null=True, verbose_name='Compañia')),
                ('direccion', models.CharField(blank=True, help_text='Dirección de entrega', max_length=255, null=True, verbose_name='Dirección')),
                ('pais', models.CharField(blank=True, help_text='Pais de entrega', max_length=255, null=True, verbose_name='Pais')),
                ('estado_pais', models.CharField(blank=True, help_text='Estado del pais de entregas', max_length=255, null=True, verbose_name='Estado')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad de entrega', max_length=255, null=True, verbose_name='Ciudad')),
                ('zip', models.CharField(blank=True, help_text='Codigo Postal de entrega', max_length=255, null=True, verbose_name='codigo postal')),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico del cliente', max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono del cliente', max_length=20, null=True, verbose_name='Teléfono')),
                ('estado', models.TextField(choices=[('Pagado', 'Pagado'), ('En Camino', 'En Camino'), ('Recibido', 'Recibido')], default='Pagado', help_text='Estado actual del pedido', max_length=50, verbose_name='Estado del Pedido')),
                ('descripcion_adicional', models.TextField(blank=True, help_text='Información adicional sobre el pedido', null=True, verbose_name='Descripción Adicional')),
                ('fecha_compra', models.DateField(help_text='Fecha en que se realizó el pedido', verbose_name='Fecha de Compra')),
                ('fecha_entrega', models.DateField(blank=True, help_text='Fecha estimada de entrega', null=True, verbose_name='Fecha de Entrega')),
                ('producto', models.ForeignKey(help_text='El producto asociado al pedido', on_delete=django.db.models.deletion.CASCADE, to='TiendaOnline.producto', verbose_name='Producto')),
            ],
        ),
    ]
