# Generated by Django 5.2 on 2025-05-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='isv',
            field=models.DecimalField(decimal_places=2, default=0.15, help_text='Impuesto sobre ventas', max_digits=10, verbose_name='ISV'),
        ),
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.CharField(blank=True, choices=[('blanco', 'Blanco'), ('rojo', 'Rojo'), ('azul', 'Azul')], help_text='Colores disponibles del producto', max_length=50, null=True, verbose_name='Colores'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], help_text='Tamaño del producto', max_length=3, null=True, verbose_name='Tamaño'),
        ),
    ]
