# Generated by Django 5.2 on 2025-06-20 16:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.CharField(max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pais',
            field=models.CharField(max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='es_movimiento_interno',
            field=models.BooleanField(default=False, verbose_name='Movimiento interno (no comercial)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.TextField(blank=True, help_text='Imagen del producto codificada en Base64', null=True, verbose_name='Imagen en Base64'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_cliente',
            field=models.CharField(max_length=100, null=True, verbose_name='Apellido del Cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_pais',
            field=models.CharField(max_length=100, null=True, verbose_name='Estado/Provincia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_cliente',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='zip',
            field=models.CharField(max_length=20, null=True, verbose_name='Código Postal'),
        ),
        migrations.CreateModel(
            name='CarritoTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_prod', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad en Carrito')),
                ('cantidad_temp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Temporal (reservado)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('expirado', models.BooleanField(default=False, verbose_name='¿Expirado?')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_temp', to='TiendaOnline.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_temp', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carrito Temporal',
                'verbose_name_plural': 'Carritos Temporales',
                'ordering': ['-fecha_actualizacion'],
                'unique_together': {('usuario', 'producto')},
            },
        ),
        migrations.DeleteModel(
            name='ISVPais',
        ),
    ]
