# Generated by Django 5.2 on 2025-05-19 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='apellido_cliente',
            field=models.CharField(blank=True, help_text='El apellido del cliente que realizó el pedido', max_length=255, null=True, verbose_name='Apellido del Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('En Camino', 'En Camino'), ('Recibido', 'Recibido')], default='Pagado', help_text='Estado actual del pedido', max_length=50, verbose_name='Estado del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(help_text='El nombre del cliente que realizó el pedido', max_length=255, verbose_name='Nombre del Cliente'),
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad de productos en el pedido', verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio del producto al momento de la compra', max_digits=10, verbose_name='Precio Unitario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_pedido', to='TiendaOnline.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaOnline.producto')),
            ],
            options={
                'verbose_name': 'Producto del Pedido',
                'verbose_name_plural': 'Productos del Pedido',
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
