# Generated by Django 5.2 on 2025-05-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0002_pedido_isv_producto_colores_producto_tamaño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='pruebas', verbose_name='Imagen del Producto'),
        ),
    ]
