# Generated by Django 5.2 on 2025-05-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0002_remove_pedido_cantidad_remove_pedido_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproducto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio del producto al momento de la compra', max_digits=10, verbose_name='Precio Unitario'),
        ),
    ]
