# Generated by Django 5.2 on 2025-06-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0002_alter_usuario_pais_alter_pedido_pais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tamaño',
        ),
        migrations.AddField(
            model_name='producto',
            name='tamano',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], help_text='Tamaño del producto', max_length=3, null=True, verbose_name='tamano'),
        ),
    ]
