# Generated by Django 5.2 on 2025-05-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.TextField(blank=True, help_text='Imagen del producto codificada en Base64', null=True, verbose_name='Imagen en Base64'),
        ),
    ]
