# Generated by Django 5.2 on 2025-05-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0003_alter_producto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
    ]
