# Generated by Django 5.2 on 2025-05-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0003_alter_pedidoproducto_precio_unitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id',
            new_name='id_pedido',
        ),
        migrations.DeleteModel(
            name='PedidoProducto',
        ),
    ]
