# Generated by Django 5.2 on 2025-05-19 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0004_rename_id_pedido_id_pedido_delete_pedidoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(default='', help_text='Producto asociado al pedido', on_delete=django.db.models.deletion.CASCADE, to='TiendaOnline.producto', verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
