# Generated by Django 5.2 on 2025-05-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('M', 'Mujeres'), ('H', 'Hombres')], help_text='Tamaño del producto', max_length=3, null=True, verbose_name='Categoria'),
        ),
    ]
