# Generated by Django 5.2 on 2025-05-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0004_remove_usuario_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido_cliente',
            field=models.CharField(max_length=100, null=True, verbose_name='Apellido del Cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_pais',
            field=models.CharField(max_length=100, null=True, verbose_name='Estado/Provincia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_cliente',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='zip',
            field=models.CharField(max_length=20, null=True, verbose_name='Código Postal'),
        ),
    ]
