# Generated by Django 5.2 on 2025-05-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0005_pedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=0, help_text='Cantidad de productos que se compraron', verbose_name='Cantidad de productos'),
        ),
    ]
