# Generated by Django 5.2 on 2025-05-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0005_alter_usuario_apellido_cliente_alter_usuario_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.IntegerField(null=True, verbose_name='País'),
        ),
    ]
