# Generated by Django 5.2 on 2025-05-08 20:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0005_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='colores',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='Selecciona un color para el producto', image_field=None, max_length=25, null=True, samples=None, verbose_name='Color'),
        ),
    ]
