# Generated by Django 5.2 on 2025-05-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0006_alter_producto_colores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='colores',
            field=models.TextField(blank=True, help_text='Selecciona un color para el producto', null=True, verbose_name='Color'),
        ),
    ]
