# Generated by Django 5.2 on 2025-05-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0006_alter_usuario_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.CharField(max_length=100, null=True, verbose_name='País'),
        ),
    ]
