# Generated by Django 5.2 on 2025-05-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0007_alter_producto_colores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='colores',
            field=models.CharField(help_text='Color en formato hexadecimal (ej. #FF0000)', max_length=7, verbose_name='Color Hexadecimal'),
        ),
    ]
