# Generated by Django 5.2 on 2025-05-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0008_alter_pedido_pais_delete_isvpais'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='es_movimiento_interno',
            field=models.BooleanField(default=False, verbose_name='Movimiento interno (no comercial)'),
        ),
    ]
