# Generated by Django 5.2 on 2025-05-29 18:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0009_pedido_es_movimiento_interno'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_prod', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('cantidad_temp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Temporal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_temp', to='TiendaOnline.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_temp', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carrito Temporal',
                'verbose_name_plural': 'Carritos Temporales',
                'unique_together': {('usuario', 'producto')},
            },
        ),
    ]
