# Generated by Django 5.2 on 2025-05-30 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0010_carritotemp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritotemp',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'Carrito Temporal', 'verbose_name_plural': 'Carritos Temporales'},
        ),
        migrations.AddField(
            model_name='carritotemp',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de última actualización'),
        ),
        migrations.AddField(
            model_name='carritotemp',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='carritotemp',
            name='limite_compra',
            field=models.PositiveIntegerField(default=10, help_text='Cantidad máxima que un usuario puede comprar de este producto', verbose_name='Límite de compra por usuario'),
        ),
        migrations.AlterField(
            model_name='carritotemp',
            name='cantidad_prod',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad en Carrito'),
        ),
        migrations.AlterField(
            model_name='carritotemp',
            name='cantidad_temp',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Temporal (reservado)'),
        ),
    ]
