# Generated by Django 5.2 on 2025-05-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0010_alter_producto_colores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='colores',
            field=models.TextField(default='#FFFFFF', help_text='Color en formato hexadecimal (ej. #FF0000)', verbose_name='Color Hexadecimal'),
        ),
    ]
