# Generated by Django 5.2 on 2025-05-10 04:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0011_alter_producto_colores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen del producto', max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
