# Generated by Django 5.2 on 2025-05-30 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0011_alter_carritotemp_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritotemp',
            options={'verbose_name': 'Carrito Temporal', 'verbose_name_plural': 'Carritos Temporales'},
        ),
        migrations.AlterField(
            model_name='carritotemp',
            name='cantidad_prod',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='carritotemp',
            name='cantidad_temp',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Temporal'),
        ),
        migrations.AlterField(
            model_name='carritotemp',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='carritotemp',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='carritotemp',
            name='limite_compra',
            field=models.PositiveIntegerField(default=10, verbose_name='Límite de Compra'),
        ),
    ]
