# Generated by Django 5.2 on 2025-05-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0012_alter_carritotemp_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoTemp',
        ),
    ]
