# Generated by Django 5.2 on 2025-06-04 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0013_delete_carritotemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_prod', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad en Carrito')),
                ('cantidad_temp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Temporal (reservado)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('expirado', models.BooleanField(default=False, verbose_name='¿Expirado?')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_temp', to='TiendaOnline.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_temp', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carrito Temporal',
                'verbose_name_plural': 'Carritos Temporales',
                'ordering': ['-fecha_actualizacion'],
                'unique_together': {('usuario', 'producto')},
            },
        ),
    ]
