# Generated by Django 5.2 on 2025-05-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0013_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.TextField(blank=True, help_text='Imagen del producto codificada en base64', null=True, verbose_name='Imagen del Producto en Base64'),
        ),
    ]
