# Generated by Django 5.2 on 2025-06-09 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0014_carritotemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritotemp',
            name='ultima_verificacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Última Verificación'),
            preserve_default=False,
        ),
    ]
