# Generated by Django 5.2 on 2025-05-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0014_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
