# Generated by Django 5.2 on 2025-06-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0015_carritotemp_ultima_verificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritotemp',
            name='ultima_verificacion',
        ),
    ]
