# Generated by Django 5.2 on 2025-05-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0015_producto_imagen_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_base64',
            field=models.TextField(blank=True, help_text='Imagen del producto codificada en Base64', null=True, verbose_name='Imagen en Base64'),
        ),
    ]
