# Generated by Django 5.2 on 2025-05-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0016_remove_producto_imagen_alter_producto_imagen_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.TextField(choices=[('Pagado', 'Pagado'), ('En Camino', 'En Camino'), ('Recibido', 'Recibido')], default='Pagado', help_text='Estado actual del pedido', max_length=50, verbose_name='Estado del Pedido'),
        ),
    ]
