# Generated by Django 5.2 on 2025-05-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0017_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Apellido_cliente',
            field=models.CharField(help_text='El apellido del cliente que realizó el pedido', max_length=255, null=True, verbose_name='Apellido del Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='Ciudad',
            field=models.CharField(blank=True, help_text='Dirección de entrega', max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='Estado',
            field=models.CharField(blank=True, help_text='Dirección de entrega', max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='company',
            field=models.CharField(blank=True, help_text='Dirección de entrega', max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pais',
            field=models.CharField(blank=True, help_text='Dirección de entrega', max_length=255, null=True, verbose_name='Dirección'),
        ),
    ]
