# Generated by Django 5.2 on 2025-05-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0018_pedido_apellido_cliente_pedido_ciudad_pedido_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Ciudad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='Estado',
            new_name='estado_pais',
        ),
    ]
