# Generated by Django 5.2 on 2025-05-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0019_rename_ciudad_pedido_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Apellido_cliente',
            new_name='apellido_cliente',
        ),
    ]
