# Generated by Django 5.2 on 2025-05-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0020_rename_apellido_cliente_pedido_apellido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='zip',
            field=models.CharField(blank=True, help_text='Codigo Postal de entrega', max_length=255, null=True, verbose_name='codigo postal'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad de entrega', max_length=255, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='company',
            field=models.CharField(blank=True, help_text='Compañia a entregar', max_length=255, null=True, verbose_name='Compañia'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pais',
            field=models.CharField(blank=True, help_text='Estado del pais de entrega', max_length=255, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pais',
            field=models.CharField(blank=True, help_text='Pais de entrega', max_length=255, null=True, verbose_name='Pais'),
        ),
    ]
